### PR TITLE
chore: Update to wasmtime v17

### PR DESCRIPTION
**Pull request by saulecabrera**

### CODE REVIEW

**Review by ianks — APPROVED** [review]

**Comment by ianks** [comment]
Seems like ruby-head may be busted, it's a moving target so fine to ignore

**Comment by saulecabrera** [comment]
@ianks Thanks for the heads up. I was thinking, would you be fine if we softened the CI criteria for Ruby head? Emit a warning instead of an error if there are failures?

**Comment by saulecabrera** [comment]
I'll merge this as is and open a new issue to discuss options for Ruby head.

**Comment by saulecabrera** [comment]
https://github.com/bytecodealliance/wasmtime-rb/issues/286, feel free to leave any thoughts there and I'm happy to follow up with a PR once/if we settle on a particular solution.

**Pull request merged**
