### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jbourassa**
Run:
- `bundle update` for dev gems, all of which are dev dependencies
- `cargo update` for the gem's crates, many of which are production dependencies
- `cargo update` in `examples/rust-crate` to fix dependabot security warnings

Includes magnus bump to 0.6.2 which will bring back rb-sys' `stable-api` feature.

### CODE REVIEW

**Comment by jbourassa** [comment]
I don't understand how pushing a new version of this branch closed the PR 😕 -- will re-open.

**Review by saulecabrera — COMMENTED** [review]
I'm a bit confused as to why only `examples/rust-crate/Cargo.lock` is updated as of the latest commit. It seems that the changes in https://github.com/bytecodealliance/wasmtime-rb/commit/5df6081d86bc50ef53cf5d7b82332542d41aa62a is what we want?

**Comment by jbourassa** [comment]
Oops, bad commit on my part, sorry about that. I left `Cargo.lock` and `Gemfile.lock` uncommitted 🤦.

Should be good now.

**Review by saulecabrera — APPROVED** [review]
Thanks!

**Pull request merged**
