### PR TITLE
chore: Update rb-sys

### PR DESCRIPTION
**Pull request by saulecabrera**
This commit updates rb-sys to the latest version. I'm hoping that this will fix the failures that are currently in main

### CODE REVIEW

**Comment by saulecabrera** [comment]
@ianks I'm mostly flying blind here, but do you think that this change will help resolve the failures in `main`: https://github.com/bytecodealliance/wasmtime-rb/actions/runs/8816496220/job/24246997925?

**Comment by saulecabrera** [comment]
Ah, I'll confirm by running the action with this branch.

**Comment by ianks** [comment]
yes 0.9.97 should fix that issue, as well add support for `aarch64-linux-musl`

**Comment by saulecabrera** [comment]
Thanks, yeah that fixed it, there's also an issue with `x64-mingw32` I believe we need to exclude it give that 3.0 is no longer considered stable? See https://github.com/bytecodealliance/wasmtime-rb/pull/317/commits/68fb3d5b1de607d85123e6f2f35f67c9b36fb42c

**Comment by saulecabrera** [comment]
Yeah, excluding `x64-mingw32` fixed the issue https://github.com/bytecodealliance/wasmtime-rb/actions/runs/8834566920

**Review by jbourassa — APPROVED** [review]

**Pull request merged**
