### PR TITLE
Update magnus 0.6.0 [Attempt #2]

### PR DESCRIPTION
**Pull request by Youssef-Mak**

### CODE REVIEW

**Comment by ianks** [comment]
Awesome stuff. Don't worry about the windows test failures for now, I'll see what I can do about that (it's not from this PR).

**Comment by ianks** [comment]
Awesome stuff. Don't worry about the windows test failures for now, I'll see what I can do about that (it's not from this PR).

**Comment by ianks** [comment]
Taking a look now

**Comment by jbourassa** [comment]
Superseded by #205 which I just merged.

**Pull request closed without merging**
